buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.2.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.21'
        classpath 'io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.23.8'
        classpath 'com.dropbox.dependency-guard:dependency-guard:0.5.0'
        classpath 'org.jetbrains.kotlinx:binary-compatibility-validator:0.18.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
