apply plugin: 'com.android.library'
apply plugin: 'kotlin-parcelize'
apply plugin: 'io.gitlab.arturbosch.detekt'
apply plugin: 'com.dropbox.dependency-guard'
apply from: './maven.gradle'

android {
    namespace 'github.com.st235.expandablebottombar'

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 37
        compileSdk 37
        versionCode project.property('VERSION_CODE') as int
        versionName project.property('VERSION_NAME')

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            versionNameSuffix '-debug'
        }

        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlin {
        jvmToolchain(17)
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

dependencyGuard {
    configuration("releaseRuntimeClasspath")
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.2.10'

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.9.8'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.23.0'
    testImplementation 'org.hamcrest:hamcrest-library:3.0'
    testImplementation 'androidx.test:core:1.7.0'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:6.3.0'
    testImplementation 'org.robolectric:robolectric:4.16.1'

}
